version: '3.4'

networks:
  frontend:

services:
  fehospital:
    container_name: fehospital
    image: hmtd79/fe:v1
    networks:
      - frontend
    ports:
      - 5000:3000
     
volumes:
    my-volume:
      
  
