version: '3.4'

networks:
  hospital:

services:
  hospitalservice:
    container_name: behospital
    image: hmtdproj/hospital:v3
    networks:
      - hospital
    ports:
      - 8080:8080
    environment:
      - ConnectionStrings__Hospital=Server=10.36.9.252,1433;Database=HOSPITAL_DB;User Id=sa;Password=@357ithmtd;TrustServerCertificate=True;
  fehospital:
    container_name: fehospital
    image: hmtd79/fe:v1
    networks:
      - hospital
    ports:
      - 5000:3000
  
volumes:
    my-volume:
      
  
