version: '3.4'

networks:
  hospital:

services:
  hospitaldb:
    container_name: hospitaldb
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - hospital
    ports:
      - 1433:1433
    volumes:
       - d:/ProjectDeploy/var/opt/mssql-data:/var/opt/mssql/data
       - d:/ProjectDeploy/var/opt/mssql-log:/var/opt/mssql/log
       - d:/ProjectDeploy/var/opt/mssql-secret:/var/opt/mssql/secrets
volumes:
    my-volume:
    # certs:
    #   driver: local
    # esdata01:
    #    driver: local
    # kibanadata:
    #   driver: local
    # metricbeatdata01:
    #   driver: local
    # filebeatdata01:
    #   driver: local
    # logstashdata01:
    #   driver: local
      
  
