version: '3.4'

networks:
  hospital:

services:
  hospitaldb:
    container_name: hospitaldb
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - hospital
    ports:
      - 1433:1433
    volumes:
       - d:/ProjectDeploy/var/opt/mssql-data:/var/opt/mssql/data
       - d:/ProjectDeploy/var/opt/mssql-log:/var/opt/mssql/log
       - d:/ProjectDeploy/var/opt/mssql-secret:/var/opt/mssql/secrets

  hospitalservice:
    container_name: hospitalservice
    image: hmtdproj/hospital:v2
    networks:
      - hospital
    ports:
      - 8080:8080
    environment:
      - ConnectionStrings__Hospital=Server=host.docker.internal,1433;Database=HOSPITAL_DB;User Id=sa;Password=password@12345#;TrustServerCertificate=True;
  fehospital:
    container_name: fehospital
    image: hmtd79/fe:v1
    networks:
      - hospital
    ports:
      - 5000:3000
  
volumes:
    my-volume:
      
  
